### ISSUE TITLE
 fatal error: lzo/lzo1x.h: No such file or directory during make pg_install

### ISSUE THREAD

**Issue by changchichung** [wal-g/wal-g#397]
OS: ubuntu 14.04 x64
golang: 1.9.1

here is the complete compile log
```
2019-09-02 18:02:00 [changch@hqdc034 wal-g]$ make install
go get -u github.com/golang/dep/cmd/dep
go get -u golang.org/x/lint/golint
2019-09-02 18:02:07 [changch@hqdc034 wal-g]$ make deps
git submodule update --init
dep ensure
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  cloud.google.com/go
  ✗  github.com/go-yaml/yaml

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.

sed -i 's|\(#cgo LDFLAGS:\) .*|\1 -Wl,-Bstatic -llzo2 -Wl,-Bdynamic|' vendor/github.com/cyberdelia/lzo/lzo.go
./link_brotli.sh
-- The C compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for log2
-- Looking for log2 - not found
-- Looking for log2
-- Looking for log2 - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist
make[1]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[2]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlicommon-static
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[  2%] Building C object CMakeFiles/brotlicommon-static.dir/c/common/dictionary.c.o
[  4%] Building C object CMakeFiles/brotlicommon-static.dir/c/common/transform.c.o
Linking C static library libbrotlicommon-static.a
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[  4%] Built target brotlicommon-static
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlienc-static
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[  6%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/backward_references.c.o
[  8%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/backward_references_hq.c.o
[ 10%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/bit_cost.c.o
[ 12%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/block_splitter.c.o
[ 14%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/brotli_bit_stream.c.o
[ 16%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/cluster.c.o
[ 18%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/compress_fragment.c.o
[ 20%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/compress_fragment_two_pass.c.o
[ 22%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/dictionary_hash.c.o
[ 24%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/encode.c.o
[ 26%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/encoder_dict.c.o
[ 28%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/entropy_encode.c.o
[ 30%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/histogram.c.o
[ 32%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/literal_cost.c.o
[ 34%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/memory.c.o
[ 36%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/metablock.c.o
[ 38%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/static_dict.c.o
[ 40%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/utf8_util.c.o
Linking C static library libbrotlienc-static.a
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 40%] Built target brotlienc-static
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlidec-static
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 42%] Building C object CMakeFiles/brotlidec-static.dir/c/dec/bit_reader.c.o
[ 44%] Building C object CMakeFiles/brotlidec-static.dir/c/dec/decode.c.o
[ 46%] Building C object CMakeFiles/brotlidec-static.dir/c/dec/huffman.c.o
[ 48%] Building C object CMakeFiles/brotlidec-static.dir/c/dec/state.c.o
Linking C static library libbrotlidec-static.a
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 48%] Built target brotlidec-static
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotli
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 51%] Building C object CMakeFiles/brotli.dir/c/tools/brotli.c.o
Linking C executable brotli
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 51%] Built target brotli
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlicommon
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 53%] Building C object CMakeFiles/brotlicommon.dir/c/common/dictionary.c.o
[ 55%] Building C object CMakeFiles/brotlicommon.dir/c/common/transform.c.o
Linking C shared library libbrotlicommon.so
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 55%] Built target brotlicommon
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlidec
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 57%] Building C object CMakeFiles/brotlidec.dir/c/dec/bit_reader.c.o
[ 59%] Building C object CMakeFiles/brotlidec.dir/c/dec/decode.c.o
[ 61%] Building C object CMakeFiles/brotlidec.dir/c/dec/huffman.c.o
[ 63%] Building C object CMakeFiles/brotlidec.dir/c/dec/state.c.o
Linking C shared library libbrotlidec.so
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 63%] Built target brotlidec
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlienc
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 65%] Building C object CMakeFiles/brotlienc.dir/c/enc/backward_references.c.o
[ 67%] Building C object CMakeFiles/brotlienc.dir/c/enc/backward_references_hq.c.o
[ 69%] Building C object CMakeFiles/brotlienc.dir/c/enc/bit_cost.c.o
[ 71%] Building C object CMakeFiles/brotlienc.dir/c/enc/block_splitter.c.o
[ 73%] Building C object CMakeFiles/brotlienc.dir/c/enc/brotli_bit_stream.c.o
[ 75%] Building C object CMakeFiles/brotlienc.dir/c/enc/cluster.c.o
[ 77%] Building C object CMakeFiles/brotlienc.dir/c/enc/compress_fragment.c.o
[ 79%] Building C object CMakeFiles/brotlienc.dir/c/enc/compress_fragment_two_pass.c.o
[ 81%] Building C object CMakeFiles/brotlienc.dir/c/enc/dictionary_hash.c.o
[ 83%] Building C object CMakeFiles/brotlienc.dir/c/enc/encode.c.o
[ 85%] Building C object CMakeFiles/brotlienc.dir/c/enc/encoder_dict.c.o
[ 87%] Building C object CMakeFiles/brotlienc.dir/c/enc/entropy_encode.c.o
[ 89%] Building C object CMakeFiles/brotlienc.dir/c/enc/histogram.c.o
[ 91%] Building C object CMakeFiles/brotlienc.dir/c/enc/literal_cost.c.o
[ 93%] Building C object CMakeFiles/brotlienc.dir/c/enc/memory.c.o
[ 95%] Building C object CMakeFiles/brotlienc.dir/c/enc/metablock.c.o
[ 97%] Building C object CMakeFiles/brotlienc.dir/c/enc/static_dict.c.o
[100%] Building C object CMakeFiles/brotlienc.dir/c/enc/utf8_util.c.o
Linking C shared library libbrotlienc.so
make[3]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[100%] Built target brotlienc
make[2]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[1]: Leaving directory `/home/changch/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
2019-09-02 18:02:35 [changch@hqdc034 wal-g]$ make pg_install
(cd main/pg && go build -o wal-g -tags "brotli lzo" -ldflags "-s -w -X github.com/wal-g/wal-g/cmd.BuildDate=`date -u +%Y.%m.%d_%H:%M:%S` -X github.com/wal-g/wal-g/cmd.GitRevision=`git rev-parse --short HEAD` -X github.com/wal-g/wal-g/cmd.WalgVersion=`git tag -l --points-at HEAD`")
# github.com/wal-g/wal-g/vendor/github.com/jedib0t/go-pretty/text
../../vendor/github.com/jedib0t/go-pretty/text/align.go:97:14: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/string.go:29:10: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/string.go:163:10: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/string.go:166:44: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/wrap.go:101:98: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/wrap.go:130:85: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/wrap.go:172:75: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/wrap.go:185:50: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/wrap.go:191:51: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/wrap.go:220:51: undefined: strings.Builder
../../vendor/github.com/jedib0t/go-pretty/text/string.go:166:44: too many errors
# github.com/wal-g/wal-g/vendor/github.com/cyberdelia/lzo
../../vendor/github.com/cyberdelia/lzo/lzo.go:5:23: fatal error: lzo/lzo1x.h: No such file or directory
 #include <lzo/lzo1x.h>
                       ^
compilation terminated.
make: *** [pg_build] Error 2
```

any suggestions ? or ubuntu 14.04 is just too old to build ?

**Comment by changchichung** [comment]
nop , it's not working in ubuntu 18.04 either . this machine is a whole new install vps .

OS: ubuntu 18.04 x64
golang: 1.10.4

here is the log
```
administrator@pgwal:~$ go get github.com/wal-g/wal-g
package github.com/wal-g/wal-g: no Go files in /home/administrator/go/src/github.com/wal-g/wal-g
administrator@pgwal:~$ cd go/src/github.com/wal-g/wal-g/
administrator@pgwal:~/go/src/github.com/wal-g/wal-g$ make install
go get -u github.com/golang/dep/cmd/dep
go get -u golang.org/x/lint/golint

administrator@pgwal:~/go/src/github.com/wal-g/wal-g$ make deps
git submodule update --init
dep ensure
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  cloud.google.com/go
  ✗  github.com/go-yaml/yaml

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.

sed -i 's|\(#cgo LDFLAGS:\) .*|\1 -Wl,-Bstatic -llzo2 -Wl,-Bdynamic|' vendor/github.com/cyberdelia/lzo/lzo.go
./link_brotli.sh
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for log2
-- Looking for log2 - not found
-- Looking for log2
-- Looking for log2 - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist
make[1]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[2]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlicommon
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[  1%] Building C object CMakeFiles/brotlicommon.dir/c/common/dictionary.c.o
[  3%] Building C object CMakeFiles/brotlicommon.dir/c/common/transform.c.o
[  5%] Linking C shared library libbrotlicommon.so
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[  5%] Built target brotlicommon
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlienc
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[  7%] Building C object CMakeFiles/brotlienc.dir/c/enc/backward_references.c.o
[  8%] Building C object CMakeFiles/brotlienc.dir/c/enc/backward_references_hq.c.o
[ 10%] Building C object CMakeFiles/brotlienc.dir/c/enc/bit_cost.c.o
[ 12%] Building C object CMakeFiles/brotlienc.dir/c/enc/block_splitter.c.o
[ 14%] Building C object CMakeFiles/brotlienc.dir/c/enc/brotli_bit_stream.c.o
[ 16%] Building C object CMakeFiles/brotlienc.dir/c/enc/cluster.c.o
[ 17%] Building C object CMakeFiles/brotlienc.dir/c/enc/compress_fragment.c.o
[ 19%] Building C object CMakeFiles/brotlienc.dir/c/enc/compress_fragment_two_pass.c.o
[ 21%] Building C object CMakeFiles/brotlienc.dir/c/enc/dictionary_hash.c.o
[ 23%] Building C object CMakeFiles/brotlienc.dir/c/enc/encode.c.o
[ 25%] Building C object CMakeFiles/brotlienc.dir/c/enc/encoder_dict.c.o
[ 26%] Building C object CMakeFiles/brotlienc.dir/c/enc/entropy_encode.c.o
[ 28%] Building C object CMakeFiles/brotlienc.dir/c/enc/histogram.c.o
[ 30%] Building C object CMakeFiles/brotlienc.dir/c/enc/literal_cost.c.o
[ 32%] Building C object CMakeFiles/brotlienc.dir/c/enc/memory.c.o
[ 33%] Building C object CMakeFiles/brotlienc.dir/c/enc/metablock.c.o
[ 35%] Building C object CMakeFiles/brotlienc.dir/c/enc/static_dict.c.o
[ 37%] Building C object CMakeFiles/brotlienc.dir/c/enc/utf8_util.c.o
[ 39%] Linking C shared library libbrotlienc.so
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 39%] Built target brotlienc
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlidec
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 41%] Building C object CMakeFiles/brotlidec.dir/c/dec/bit_reader.c.o
[ 42%] Building C object CMakeFiles/brotlidec.dir/c/dec/decode.c.o
[ 44%] Building C object CMakeFiles/brotlidec.dir/c/dec/huffman.c.o
[ 46%] Building C object CMakeFiles/brotlidec.dir/c/dec/state.c.o
[ 48%] Linking C shared library libbrotlidec.so
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 48%] Built target brotlidec
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlicommon-static
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 50%] Building C object CMakeFiles/brotlicommon-static.dir/c/common/dictionary.c.o
[ 51%] Building C object CMakeFiles/brotlicommon-static.dir/c/common/transform.c.o
[ 53%] Linking C static library libbrotlicommon-static.a
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 53%] Built target brotlicommon-static
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlienc-static
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 55%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/backward_references.c.o
[ 57%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/backward_references_hq.c.o
[ 58%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/bit_cost.c.o
[ 60%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/block_splitter.c.o
[ 62%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/brotli_bit_stream.c.o
[ 64%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/cluster.c.o
[ 66%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/compress_fragment.c.o
[ 67%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/compress_fragment_two_pass.c.o
[ 69%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/dictionary_hash.c.o
[ 71%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/encode.c.o
[ 73%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/encoder_dict.c.o
[ 75%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/entropy_encode.c.o
[ 76%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/histogram.c.o
[ 78%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/literal_cost.c.o
[ 80%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/memory.c.o
[ 82%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/metablock.c.o
[ 83%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/static_dict.c.o
[ 85%] Building C object CMakeFiles/brotlienc-static.dir/c/enc/utf8_util.c.o
[ 87%] Linking C static library libbrotlienc-static.a
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 87%] Built target brotlienc-static
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotlidec-static
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 89%] Building C object CMakeFiles/brotlidec-static.dir/c/dec/bit_reader.c.o
[ 91%] Building C object CMakeFiles/brotlidec-static.dir/c/dec/decode.c.o
[ 92%] Building C object CMakeFiles/brotlidec-static.dir/c/dec/huffman.c.o
[ 94%] Building C object CMakeFiles/brotlidec-static.dir/c/dec/state.c.o
[ 96%] Linking C static library libbrotlidec-static.a
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 96%] Built target brotlidec-static
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
Scanning dependencies of target brotli
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[3]: Entering directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[ 98%] Building C object CMakeFiles/brotli.dir/c/tools/brotli.c.o
[100%] Linking C executable brotli
make[3]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
[100%] Built target brotli
make[2]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
make[1]: Leaving directory '/home/administrator/go/src/github.com/wal-g/wal-g/vendor/github.com/google/brotli/dist'
administrator@pgwal:~/go/src/github.com/wal-g/wal-g$ make pg_install
(cd main/pg && go build -o wal-g -tags "brotli lzo" -ldflags "-s -w -X github.com/wal-g/wal-g/cmd.BuildDate=`date -u +%Y.%m.%d_%H:%M:%S` -X github.com/wal-g/wal-g/cmd.GitRevision=`git rev-parse --short HEAD` -X github.com/wal-g/wal-g/cmd.WalgVersion=`git tag -l --points-at HEAD`")
# github.com/wal-g/wal-g/vendor/github.com/cyberdelia/lzo
../../vendor/github.com/cyberdelia/lzo/lzo.go:5:10: fatal error: lzo/lzo1x.h: No such file or directory
 #include <lzo/lzo1x.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:19: recipe for target 'pg_build' failed
make: *** [pg_build] Error 2
administrator@pgwal:~/go/src/github.com/wal-g/wal-g$ 
```

**Comment by changchichung** [comment]
OK , for that error , I have to manually compile lzo from source .
down lzo from here
http://www.oberhumer.com/opensource/lzo/
configure / make / sudo make install
then go back to wal-g and make pg_install then works.

but , why you guys move the wal-g to / ? not /usr/local/bin or somewhere else but put files in rootfs ?
that's really weird ...

**Comment by x4m** [comment]
> but , why you guys move the wal-g to / ? not /usr/local/bin or somewhere else but put files in rootfs ?
Honestly, I do not know.

We surely must do dev build easier. We are considering removing lzo and brotli dependency for dev build. PRs are welcome.

**Comment by dyson** [comment]
Try running `export CGO_LDFLAGS='-no-pie'` first before make deps.

**Comment by dyson** [comment]
I think from memory I needed `liblzo2-dev`. Try running `sudo apt-get install liblzo2-dev`.
